--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/SoyDavs/Trampoline
build-by-default: true
branches:
- main
projects:
  Trampoline:
    path: ""
    lint:
      phpstan: false   
...
